name: Generate report
author: guipublic
description: Easily compare json reports
branding:
  icon: info
  color: purple

inputs:
  token:
    description: The repository's github token.
    default: ${{ github.token }}
    required: false
  base:
    description: The report reference branch name.
    default: ${{ github.base_ref || github.ref_name }}
    required: false
  head:
    description: The report target branch name.
    default: ${{ github.head_ref || github.ref_name }}
    required: false
  report:
    description: Report freshly generated to compare to reference.
    default: gates_report.json
    required: false
  header:
    description: The top section displayed in the markdown output.
    default: |
      # Changes to circuit sizes
    required: false
  memory_report:
     description: States whether we want to generate a report of memory usage.
     default: false
     required: false
  execution_report:
    description: States whether we want to generate a report of execution times.
    default: false
    required: false

outputs:
  shell:
    description: The diff between the base report and the freshly generated report, specifically formatted for shell display
  markdown:
    description: The diff between the base report and the freshly generated report, specifically formatted for markdown display

runs:
  using: node16
  main: dist/index.js
